alias d="docker"
alias drc="docker compose"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias t="nvim $HOME/notes/todo/todo.md"
alias trash="gio trash"
alias shred="srm -l"
alias du="ncdu"
alias yt="yt-dlp --embed-metadata --embed-subs --embed-thumbnail"
alias yt-sub="yt-dlp --all-subs --convert-subs srt --skip-download"
alias yt-audio="yt-dlp -f 'ba[acodec=opus]' -S +size"

# https://www.techspeak.dev/2019/01/14/improve-your-git-flow-with-fuzzy-find.html
alias gfzf="git ls-files -m -o --exclude-standard | fzf --print0 -m -1 | xargs -0 -t -o"
