alias b="bemenu -l 10 -H 30 --fn 'Cabin 10'"

# alias sudo="doas"
alias thumb="convert cover.* -resize 96x96! -quality 65% folder.jpg"
alias bak="crsync"
alias vim="nvim"
alias t="vim $HOME/notes/todo/todo.md"
alias u="sudo apt update; sudo apt upgrade"
#alias c="kalk_cli"
alias c="calcurse"
alias fin="ledger --market balance ^assets ^liabilities"
alias trash="gio trash"
alias trash-more="srm -l"
alias ledger="ledger --strict -f $LEDGER"
alias ls="ls --color=always"
alias du="ncdu"
alias yt="yt-dlp"
alias yt-sub="yt-dlp --all-subs --convert-subs srt --skip-download"
alias flac2mp3="parallel ffmpeg -i {} -qscale:a 2 {.}.mp3 ::: ./*.flac"

# https://www.techspeak.dev/2019/01/14/improve-your-git-flow-with-fuzzy-find.html
alias gfzf="git ls-files -m -o --exclude-standard | fzf --print0 -m -1 | xargs -0 -t -o"
