#!/usr/bin/env python3

import sys
import i3ipc as i3  # type: ignore
from typing import Literal, Iterator

def trunc(x: str, n: int = 25) -> str:
    return x[:n] + "…" if len(x) > n + 1 else x

def print_con(con: i3.Con, prefix: str = ""):
    if con.focused:
        print("\033[1m", end="")
    print(f"{prefix}"
        f"#{con.id} "
        f"{con.type}/{con.layout} "
        f"[{', '.join(con.marks)}] "
        f"\033[3m{trunc(con.name or '')}\033[0m"
        f"{'*' if con.focused else ''}")
    if con.focused:
        print("\033[0m", end="")
    for node in con.nodes:
        print_con(node, prefix=prefix + " │ ")

if __name__ == "__main__":
    conn = i3.Connection()
    tree: i3.Con = conn.get_tree()
    focused: i3.Con = tree.find_focused()
    workspace: i3.Con = focused.workspace()
    for workspace in tree.workspaces():
        print_con(workspace)
        print()
