#!/usr/bin/env python3
# Pack workspaces tight, then go to the new window at the end.

from i3ipc import Connection  # type: ignore

if __name__ == "__main__":
    conn = Connection()
    workspaces = conn.get_tree().workspaces()
    i = 1
    for ws in workspaces:
        if ws.nodes:
            if ws.num != i:
                cmd = f"move container to workspace number {i}"
                for c in ws.nodes:
                    if err := c.command(cmd)[0].error:
                        print(err)
            i += 1
    conn.command(f"workspace number {i}")
