#!/usr/bin/env python3
# Pack workspaces tight, then go to a new workspace at the end.

import sys
from i3ipc import Connection  # type: ignore

if __name__ == "__main__":
    conn = Connection()
    tree = conn.get_tree()
    focused = tree.find_focused()
    workspaces = tree.workspaces()
    i = 1
    for ws in workspaces:
        if ws.nodes:
            if ws.num != i:
                cmd = f"move container to workspace number {i}"
                for c in ws.nodes:
                    if err := c.command(cmd)[0].error:
                        print(err)
            i += 1
    try:
        move = sys.argv[1] == "move"
    except IndexError:
        move = False

    if move:
        focused.command(f"move container to workspace number {i}")
    conn.command(f"workspace number {i}")
