#!/bin/sh
# This directory contains scripts to setup a system the way I like it.
# Subdirectories contain scripts to install software and themes that are
# outdated or not available in the standard repositories.

case $(lsb_release -si) in
    Debian)
        echo Bootstrap for Debian... >&2
        cd "$(dirname "$0")"
        setup/packages-core
        setup/firewall
    ;;
    *)
        echo No bootscript for this distribution. >&2
        exit 1
    ;;
esac
