#!/bin/sh
# This directory contains scripts to setup a system the way I like it.
# Subdirectories contain scripts to install software and themes that are
# outdated or not available in the standard repositories.

case $(lsb_release -si) in
    Debian)
        echo Debian
        ;;
    Alpine)
        echo Alpine
        ;;
    *)
        echo Unsupported
        exit 1
esac
