#!/bin/sh
# This directory contains scripts to setup a system the way I like it.
# Subdirectories contain scripts to install software and themes that are
# outdated or not available in the standard repositories.

case $(lsb_release -si) in
    Debian)
        echo On Debian...
        sudo apt-get install -y findutils coreutils
    ;;
esac

cd "$(dirname "$0")"
find -L "." -mindepth 2 -type f -executable ! -name "*##*" \
        | sort | while IFS= read -r SCRIPT; do
    echo "Running $SCRIPT"
    # if ! "$SCRIPT"; then
    #     echo "Error: bootstrap '$SCRIPT' failed" >&2
    #     exit 1
    # fi
done
