#!/bin/sh
# keyd - Keyboard remapper

# SOURCE: https://github.com/rvaiya/keyd
# ALPINE: https://pkgs.alpinelinux.org/package/edge/community/x86_64/keyd
# DEBIAN: -
set -eu

if ! which keyd > /dev/null; then
    mkdir -p ~/.builds
    sudo apt install -y make gcc libudev-dev
    git clone https://github.com/rvaiya/keyd ~/.builds/keyd
    cd ~/.builds/keyd
    make
    sudo make install
    sudo systemctl enable keyd
    sudo systemctl start keyd
fi

# also set setxkbmap -option compose:menu
# <https://gist.githubusercontent.com/rvaiya/be31f42049a4b5ad46666a8e120d9843/>
# <https://cgit.freedesktop.org/xorg/proto/x11proto/tree/XF86keysym.h>
#
echo "Updating keyd config..." >&2
sudo mkdir -p /etc/keyd
sudo tee /etc/keyd/default.conf > /dev/null <<EOF
[ids]

# Microsoft Keyboard
045e:07a5
# Laptop keyboard
0001:0001

[global]
chord_timeout = 50
overload_tap_timeout = 300
oneshot_timeout = 1000
default_layout = qwerty_shifted

[qwerty_shifted:layout]
# Shift right hand one key to the right
y = noop
u = y
i = u
o = i
p = o
[ = p
] = backslash

h = noop
j = h
k = j
l = k
; = l
' = ;
enter = '

# z = lettermod(control, z, 100, 200)
# x = lettermod(alt, x, 100, 200)
z = z
x = x

# ...
n = noop
m = n
, = m
. = ,
/ = .
rightshift = /
# / = lettermod(alt, ., 100, 200)
# rightshift = lettermod(control, /, 100, 200)

[colemakdh_shifted:layout]
q = q
w = w
e = f
r = p
t = b
u = j
i = l
o = u
p = y
[ = ;
] = backslash

a = a
s = r
d = s
f = t
g = g
j = m
k = n
l = e
; = i
' = o
enter = '

# z = lettermod(control, z, 100, 200)
# x = lettermod(alt, x, 100, 200)
z = z
x = x
c = c
v = d
b = v
m = k
, = h
. = ,
/ = .
rightshift = /
# / = lettermod(alt, ., 100, 200)
# rightshift = lettermod(control, /, 100, 200)


[main]
capslock = backspace
leftshift = oneshot(shift)
leftcontrol = oneshot(control)
leftmeta = oneshot(alt)

# Thumb keys
leftalt = overload(fnL, escape)
rightalt = oneshot(symbol)
compose = overloadt2(fnR, enter, 150)
rightcontrol = overloadt2(fnR, enter, 150)


[empty]


# Bare control/alt presses are still possible
[control]
z = timeout(C-z, 400, leftcontrol)
rightshift = timeout(C-/, 400, rightcontrol)


[alt]
x = timeout(A-x, 400, leftalt)
/ = timeout(A-., 400, rightalt)


# If I could clear the shifted oneshot layer but activate it as non-oneshot, 
# this would be the way to go, I think
# [shift]
# rightalt = layerm(symbol, compose)

[symbol]
leftshift = swap(shift)
q = !
w = [
e = +
r = #
t = ]

u = ^
i = 7
o = 8
p = 9
[ = oneshotm(symbol2, .)
] = @

a = *
s = (
d = -
f = =
g = )

j = ~
k = 4
l = 5
; = 6
' = 0
enter = grave

z = &
x = {
c = $
v = _
b = }

m = %
, = 1
. = 2
/ = 3
rightshift = /


[symbol2]
[ = macro(backspace :)


[fnL:M]
# Still allow bare presses of meta key by combining them
rightcontrol = overload(fnR, rightmeta)
compose = overload(fnR, rightmeta)
leftshift = overload(shift, leftshift)

space = swapm(empty, compose)

tab = delete
q = home
w = up
e = end
r = pageup

capslock = backspace
a = left
s = down
d = right
f = pagedown

x = oneshot(meta)
c = oneshot(control)
v = oneshot(alt)
# TODO: c+v = oneshot(control+alt)
# oneshot,swap

' = macro(esc ;)

[control+fnL]
tab = delete
q = C-q
w = C-w
e = C-e
r = C-r
t = C-t

a = C-a
s = C-s
d = C-d
f = C-f
g = C-g

z = C-z
x = C-x
c = C-c
v = C-v
b = C-b

# TODO: fallthrough. instead of q, fall through to current layout
[alt+fnL]
tab = delete
q = A-q
w = A-w
e = A-e
r = A-r
t = A-t

a = A-a
s = A-s
d = A-d
f = A-f
g = A-g

z = A-z
x = A-x
c = A-c
v = A-v
b = A-b

[fnR:M]
# Still allow bare presses of meta key by combining them
leftalt = overload(fnL, leftmeta)
leftshift = overload(shift, rightshift)

u = scrolllock
i = f7
o = f8
p = f9
[ = f12
] = insert

j = sysrq
k = f4
l = f5
; = f6
apostrophe = f11
enter = print

m = pause
, = f3
. = f2
/ = f1
rightshift = f10


# Layouts are very hard to accidentally toggle this way
[fnL+fnR]
space = setlayout(qwerty_shifted)
rightalt = setlayout(colemakdh_shifted)
leftshift = capslock


[extra]
# XF86WLAN / 0xf6. See also rfkill for XF86RFKill
tab = wlan
# XF86AudioPrev
q = previoussong
# XF86AudioRaiseVolume
w = volumeup
# XF86AudioNext
e = nextsong
# XF86AudioStop
r = stopcd
# XF86MonBrightnessUp
t = brightnessup

# XF86TouchpadToggle
capslock = f21
# XF86AudioRewind
a = rewind
# XF86AudioLowerVolume
s = volumedown
# XF86AudioForward
d = fastforward
# XF86AudioPlay
f = playpause
# XF86KbdBrightnessDown
g = brightnessdown

# XF86Bluetooth / 0xf5
leftshift = bluetooth
# XF86AudioMicMute
z = f20
# XF86AudioMute
x = mute
# XF86AudioPreset / 0xdd
c = sound
# XF86AudioRecord
v = record
b = noop


EOF

sudo keyd reload
