#!/bin/sh
# keyd - Keyboard remapper

# SOURCE: https://github.com/rvaiya/keyd
# ALPINE: https://pkgs.alpinelinux.org/package/edge/community/x86_64/keyd
# DEBIAN: -
set -eu

if ! which keyd > /dev/null; then
    mkdir -p ~/.builds
    sudo apt install -y make gcc libudev-dev
    git clone https://github.com/rvaiya/keyd ~/.builds/keyd
    cd ~/.builds/keyd
    make
    sudo make install
    sudo systemctl enable keyd
    sudo systemctl start keyd
fi

# also set setxkbmap -option compose:menu
# <https://gist.githubusercontent.com/rvaiya/be31f42049a4b5ad46666a8e120d9843/>
# <https://cgit.freedesktop.org/xorg/proto/x11proto/tree/XF86keysym.h>
#
echo "Updating keyd config..." >&2
sudo mkdir -p /etc/keyd
sudo tee /etc/keyd/default.conf > /dev/null <<EOF
[ids]

# Microsoft Keyboard
045e:07a5
# Laptop keyboard
0001:0001

[global]
chord_timeout = 50
overload_tap_timeout = 300
oneshot_timeout = 1000

[main]

leftshift = oneshot(shift)
leftcontrol = overload(control, compose)
leftmeta = overload(alt, compose)

# Thumb keys
leftalt = overload(fnL, escape)
rightalt = oneshot(symbol)
compose = overload(fnR, enter)
rightcontrol = overload(fnR, enter)

z = lettermod(control, z, 100, 200)
x = lettermod(alt, x, 100, 200)

# Shift right hand one key to the right

capslock = backspace
y = noop
h = noop
n = noop

u = y
j = h
m = n

i = u
k = j
, = m

o = i
l = k
. = ,

p = o
; = l
/ = lettermod(alt, ., 100, 200)

[ = p
' = ;
rightshift = lettermod(control, /, 100, 200)

] = backslash
enter = '


[colemakdh]
q = q
w = w
e = f
r = p
t = b
u = j
i = l
o = u
p = y
[ = ;
] = backslash

a = a
s = r
d = s
f = t
g = g
j = m
k = n
l = e
; = i
' = o
enter = '

z = z
x = x
c = c
v = d
b = v
m = k
, = h
. = ,
/ = .
rightshift = /

[symbol]
leftshift = swap(shift)
rightshift = swap(shift)
q = !
w = [
e = +
r = #
t = ]

u = ^
i = 7
o = 8
p = 9
[ = oneshotm(symbol2, .)
] = @

a = *
s = (
d = -
f = =
g = )

j = ~
k = 4
l = 5
; = 6
' = 0
enter = grave

z = &
x = {
c = $
v = _
b = }

m = %
, = 1
. = 2
/ = 3
rightshift = /

[symbol2]
[ = macro(backspace :)

# Not using [fn_:M-C] because it should be the same regardless of active layout

[fnR]
leftalt = overload(fnL, leftmeta)
space = togglem(fnR, compose)

q = M-C-q
w = M-C-w
e = M-C-e
r = M-C-r
t = M-C-t

a = M-C-a
s = M-C-s
d = M-C-d
f = M-C-f
g = M-C-g

z = M-C-z
x = M-C-x
c = M-C-c
v = M-C-v
b = M-C-b

u = M-C-y
i = M-C-u
o = M-C-i
p = M-C-o
[ = M-C-p
] = M-C-backslash

j = M-C-h
k = M-C-j
l = M-C-k
; = M-C-l
' = M-C-;
enter = M-C-'

m = M-C-n
, = M-C-m
. = M-C-/
/ = M-C-.
rightshift = M-C-/

[fnL]
compose = overload(fnR, leftmeta)
rightcontrol = overload(fnR, leftmeta)
space = swap(shift)

tab = delete
q = home
w = up
e = end
r = pageup
t = M-C-t

capslock = backspace
a = left
s = down
d = right
f = pagedown
g = M-C-g

z = M-C-z
x = M-C-x
c = M-C-c
v = M-C-v
b = M-C-b

u = M-C-y
i = M-C-u
o = M-C-i
p = M-C-o
[ = M-C-p
] = M-C-backslash

j = M-C-h
k = M-C-j
l = M-C-k
; = M-C-l
' = M-C-;
enter = M-C-'

m = M-C-n
, = M-C-m
. = M-C-/
/ = M-C-.
rightshift = M-C-/

[fn+symbol]

# XF86WLAN / 0xf6. See also rfkill for XF86RFKill
tab = wlan
# XF86AudioPrev
q = previoussong
# XF86AudioRaiseVolume
w = volumeup
# XF86AudioNext
e = nextsong
# XF86AudioStop
r = stopcd
# XF86MonBrightnessUp
t = brightnessup

# XF86TouchpadToggle
capslock = f21
# XF86AudioRewind
a = rewind
# XF86AudioLowerVolume
s = volumedown
# XF86AudioForward
d = fastforward
# XF86AudioPlay
f = playpause
# XF86KbdBrightnessDown
g = brightnessdown

# XF86Bluetooth / 0xf5
leftshift = bluetooth
# XF86AudioMicMute
z = f20
# XF86AudioMute
x = mute
# XF86AudioPreset / 0xdd
c = sound
# XF86AudioRecord
v = record
b = noop

u = scrolllock
i = f7
o = f8
p = f9
[ = f12
] = toggle(colemakdh)

j = print
k = f4
l = f5
; = f6
apostrophe = f11
enter = insert

m = pause
, = f3
. = f2
/ = f1
rightshift = f10
EOF

sudo keyd reload
