#!/bin/bash

PACKAGES=(
    greetd tuigreet
    sway
    swaylock
    waybar
    mako # Notifications
    direnv
    foot
    bemenu
    wtype
    squeekboard
    wdisplays
    xdg-utils # Provides `xdg-open`
    ufw

    intel-lpmd

    # Fonts
    fontawesome-6-free-fonts
    msimonson-anonymouspro-fonts
    jetbrains-mono-fonts-all
    levien-inconsolata-fonts

    NetworkManager-tui
    whiptail
    git-delta # More readable deltas
    pmount
    wget
    unzip
    glib2 # Provides trashbin via `gio trash`
    pass
    ncdu
    rsync
    lxpolkit
    mpv
    pinentry-qt
)

sudo dnf install ${PACKAGES[@]}
