#!/bin/bash

PACKAGES=(
    gnome-shell
    greetd tuigreet
    sway
    swaylock
    waybar
    mako # Notifications
    direnv
    foot
    bemenu
    wtype
    squeekboard
    wdisplays
    xdg-utils # Provides `xdg-open`
    ufw

    intel-lpmd
    iwlwifi-{m,d}vm-firmware
    alsa-sof-firmware
    NetworkManager-wifi
    cups
    system-config-printer
    printer-driver-brlaser

    # Fonts
    fontawesome-6-free-fonts
    msimonson-anonymouspro-fonts
    jetbrains-mono-fonts-all
    levien-inconsolata-fonts
    overpass-fonts
    cascadia-code-nf-fonts

    NetworkManager-tui
    whiptail
    git-delta # More readable deltas
    pmount
    wget
    unzip
    glib2 # Provides trashbin via `gio trash`
    pass
    ncdu
    rsync
    lxpolkit
    mpv
    pinentry-qt
    parallel
    puddletag
    wol
    udisks2-btrfs
    gocryptfs
)

sudo dnf install ${PACKAGES[@]}
