#!/bin/bash

signal() {
    echo -n "%{O2}"
    nmcli -f IN-USE,SIGNAL,SSID device wifi \
        | grep '^*' \
        | tr -s ' ' '\t' \
        | cut -f2
}

signal
while true; do
    signal
    sleep 30
done &
nmcli monitor | while read -r line; do
    signal
done
