#!/bin/sh
# Show the current window title using xtitle from github.com/baskerville/xtitle

LENGTH=100

xtitle -s | while read -r line; do
    if [ "${#line}" -gt ${LENGTH} ]; then
        echo "$(echo $line | cut -c -$LENGTH)"...
    else
        echo $line
    fi
done

# If xtitle is not available, you could do:
# bspc subscribe desktop_focus node_focus | while read e a b c; do
#     if [ "$e" = "node_focus" ]; then
#         xdotool getwindowname $c
#     else
#         echo
#     fi
# done
# However, this will not update when the x window title does
