#!/bin/sh

# Fix issue with Java applications not resizing
wmname LG3D

xsetroot -cursor_name left_ptr
xsetroot -solid '#ffffee'

bspc config border_width 2
bspc config window_gap -2
bspc config bottom_padding -2
bspc config right_padding -2
bspc config left_padding -2
bspc config top_monocle_padding 2
bspc config bottom_monocle_padding 2
bspc config right_monocle_padding 2
bspc config left_monocle_padding 2
bspc config normal_border_color '#c0b8b0'
bspc config focused_border_color '#b57614'
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config directional_focus_tightness high
bspc config initial_polarity second_child
bspc config automatic_scheme alternate
bspc config removal_adjustment true

bspc rule -a Netsurf-gtk state=tiled

bspwm-cleaner & # automatically remove empty desktops
keyboard-config & # keyboard settings
sxhkd & # keyboard shortcuts
lxpolkit & # policy kit
unclutter -root -idle 2 & # hide mouse when not in use for two seconds
redshift & # nighttime screen colours
dunst & # notifications
urxvtd -q -f -o & # terminal daemon
lf -server & # file manager daemon
polybar bspwm & # taskbar
