#!/bin/sh

# Fix issue with Java applications not resizing
wmname LG3D

xsetroot -cursor_name left_ptr
#xsetroot -solid '#606060'
xsetroot -solid '#e7e8eb'

bspc config border_width 1
bspc config window_gap 1
bspc config bottom_padding -2
bspc config right_padding -2
bspc config left_padding -2
bspc config top_monocle_padding 1
bspc config bottom_monocle_padding 1
bspc config right_monocle_padding 1
bspc config left_monocle_padding 1
bspc config normal_border_color '#000000' #'#202020' # '#104010' # '#c0c0c0'
bspc config focused_border_color '#ffffff' #'#808080' # '#e7e8eb' # '#50a050' # '#80ff80'

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config directional_focus_tightness high
bspc config initial_polarity second_child
bspc config automatic_scheme alternate
bspc config removal_adjustment true

autorun(){
    if ! pidof -x "$1" > /dev/null; then
        "$@" &
    fi
}

autorun bspwm-cleaner # automatically remove empty desktops
autorun keyboard-config # keyboard settings
autorun sxhkd # keyboard shortcuts
autorun lxpolkit # policy kit
autorun unclutter -root -idle 2 # hide mouse when not in use for two seconds
autorun redshift # nighttime screen colours
autorun dunst # notifications
autorun urxvtd -q -f -o # terminal daemon
autorun lf -server # file manager daemon
autorun dmenu-mpv --initialise # music player daemon
#autorun nm-applet # wifi applet
#autorun blueman-applet # bluetooth applet
polybar bspwm & # taskbar

bspc rule -a Netsurf-gtk state=tiled
