#!/bin/sh

# Fix issue with Java applications not resizing
wmname LG3D

sxhkd ~/.config/sxhkd/bspwm & # keybinds
polybar bspwm & # taskbar
nm-applet & # network
blueman-applet & # bluetooth

xsetroot -cursor_name left_ptr
hsetroot -solid '#ffffff'
# hsetroot -solid '#c6b2ba'
# hsetroot -tile pattern.jpg -brightness 0.82
# hsetroot -add '#dde6cc' -add '#97b466' -gradient 0

# bspc config border_width 2
# bspc config window_gap -2
# bspc config bottom_padding -2
# bspc config right_padding -2
# bspc config left_padding -2
# bspc config top_padding 2
# bspc config top_monocle_padding 0
# bspc config bottom_monocle_padding 2
# bspc config right_monocle_padding 2
# bspc config left_monocle_padding 2

bspc config border_width 2
# bspc config window_gap 14
# bspc config top_padding 18
# bspc config bottom_padding 8
# bspc config right_padding 4
# bspc config left_padding 4
bspc config window_gap -2
bspc config top_padding 32
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

bspc config top_monocle_padding -3
bspc config bottom_monocle_padding 0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0

# bspc config bottom_padding -2
# bspc config right_padding -2
# bspc config left_padding -2
# bspc config top_padding 2
# bspc config top_monocle_padding 0
# bspc config bottom_monocle_padding 2
# bspc config right_monocle_padding 2
# bspc config left_monocle_padding 2

#bspc config normal_border_color '#ead6b8'
# bspc config normal_border_color '#c3bba7'
# bspc config normal_border_color '#D9D2C2'
bspc config normal_border_color '#e0e0df'
# bspc config focused_border_color '#c95c5a'
bspc config focused_border_color '#ab6453'
bspc config pointer_modifier mod4
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
#bspc config directional_focus_tightness high
bspc config initial_polarity second_child
#bspc config automatic_scheme alternate
bspc config automatic_scheme longest_side
bspc config removal_adjustment true

bspc rule -a URxvt state=pseudo_tiled
bspc rule -a URxvt:floating state=floating
bspc rule -a Zenity layer=above
bspc rule -a Zathura state=tiled
bspc rule -a Onboard state=floating sticky=on follow=on
bspc rule -a Netsurf-gtk state=tiled

bspc monitor --reset-desktops $(seq 4)
