[terminal]
vt = 1

[default_session]
#command = "agreety --cmd /bin/sh"
command = "tuigreet --cmd 'systemd-cat --identifier=sway sway'"
user = "greetd"

[initial_session]
command = "systemd-cat --identifier=sway sway"
user = "nsbg"
