# -*- conf -*-

font=Cascadia Code:size=12,FontAwesome:size=11,JetBrains Mono:size=14:style=Light
font-bold=Cascadia Code:size=12:weight=bold,FontAwesome:size=11
font-italic=Cascadia Code:size=12:slant=italic,FontAwesome:size=11
font-bold-italic=Cascadia Code:size=12:weight=bold:slant=italic,FontAwesome:size=11
# font=CozetteHiDpi:pixelsize=26
# font-bold=CozetteHiDpi:pixelsize=26:weight=bold
# font-italic=CozetteHiDpi:pixelsize=26:slant=italic
# font-bold-italic=CozetteHiDpi:pixelsize=26:weight=bold:slant=italic
# font=Dina:size=11,Cozette:size=11,FontAwesome:size=11
# font-bold=Dina:size=11:weight=bold
# font-italic=Dina:size=11:slant=italic
# font-bold-italic=Dina:size=11:weight=bold:slant=italic
letter-spacing=0

# Gruvbox (dark, edited to have a darker black background)

[colors-dark]
background=000000
foreground=ebdbb2
regular0=282828  # black
regular1=cc241d  # red
regular2=98971a  # green
regular3=d79921  # yellow
regular4=458588  # blue
regular5=b16286  # magenta
regular6=689d6a  # cyan
regular7=a89984  # white
bright0=928374   # bright black
bright1=fb4934   # bright red
bright2=b8bb26   # bright green
bright3=fabd2f   # bright yellow
bright4=83a598   # bright blue
bright5=d3869b   # bright magenta
bright6=8ec07c   # bright cyan
bright7=ebdbb2   # bright white

[colors-light]
background=ffffff
#fbf1c7
foreground=3c3836
regular0=fbf1c7  # black
regular1=cc241d  # red
regular2=98971a  # green
regular3=d79921  # yellow
regular4=458588  # blue
regular5=b16286  # magenta
regular6=689d6a  # cyan
regular7=7c6f64  # white
bright0=928374   # bright black
bright1=9d0006   # bright red
bright2=79740e   # bright green
bright3=b57614   # bright yellow
bright4=076678   # bright blue
bright5=8f3f71   # bright magenta
bright6=427b58   # bright cyan
bright7=3c3836   # bright white
