#!/bin/sh

#bspc monitor --reset-desktops     1 2 3 4
#bspc config border_width          2
bspc config window_gap            8
bspc config border_width          1
#bspc config focused_border_color  "#676e7d"
bspc config focused_border_color  "#dddddd"
#bspc config normal_border_color   "#2f343f" 
bspc config normal_border_color   "#666666"
bspc config split_ratio           0.5
bspc config initial_polarity 	  second_child
bspc config focus_follows_pointer true

bspc rule -a '*:zathura' state=tiled

xsetroot -cursor_name left_ptr

pkill polybar; polybar bspwm &
pkill nm-applet; nm-applet &
