" Plugins
"call plug#begin()
call plug#begin(stdpath('data') . '/plugged')

    " Work with GPG-encrypted files
    Plug 'https://github.com/jamessan/vim-gnupg.git'

    " Sets working directory to project root
    Plug 'https://github.com/airblade/vim-rooter.git'

    " Browse within vim using the `lf` file manager
    Plug 'https://github.com/ptzz/lf.vim'
    Plug 'https://github.com/rbgrouleff/bclose.vim'
    let g:lf_map_keys = 0

    " Autocompletion
    " Also needs pip3 install pynvim
    Plug 'https://github.com/ncm2/ncm2'
    Plug 'https://github.com/roxma/nvim-yarp'

    " IDE capabilities for vim through LSP
    Plug 'https://github.com/autozimu/LanguageClient-neovim.git', { 'branch': 'next', 'do': 'bash install.sh' }

    " Highlight Pandoc-flavoured Markdown
    Plug 'https://github.com/vim-pandoc/vim-pandoc-syntax.git', { 'for': 'markdown' }

    " Highlight jq scripts
    Plug 'https://github.com/vito-c/jq.vim'

    " Highlight ledger/hledger journals
    Plug 'https://github.com/ledger/vim-ledger', { 'tag': 'v1.2.0' }

    " Show git/svn changes
    Plug 'https://github.com/mhinz/vim-signify.git'

    " Git wrapper to show things like blame
    Plug 'https://github.com/tpope/vim-fugitive.git'

    " Buffer tabs
    Plug 'https://github.com/ap/vim-buftabline'

call plug#end()

" Enable mouse support
set mouse=a

" Width is 79 characters by default
set textwidth=79

" Show column number, line number and relative position in status line
set ruler

" Show line numbers in left margin
set number

" Indentation behaviour
set autoindent " Copy indentation from previous line
set expandtab " Convert tabs to spaces
set shiftwidth=4 " Number of characters for indentation (> and <)
set softtabstop=4 " Tab and backspace insert and delete correct number of spaces

" Do not automatically put two spaces after a sentence
set nojoinspaces

" Backspace over indentations
set backspace=indent,eol,start

" Move to previous/next line when pressing left/right at beginning/end
set whichwrap=<,>,h,l,[,]

" Show completion menu and, on tab, complete to the longest common command
set wildmenu
set wildmode=longest,list,full

" Copy to system clipboard by default
set clipboard=unnamedplus

" Turn off background on the sign column (except when there are signs)  
highlight SignColumn ctermbg=NONE cterm=NONE guibg=NONE gui=NONE


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" File-specific configuration

if has("autocmd")
    au BufRead /tmp/mutt-* set tw=72

    augroup pandoc_syntax
        au! BufNewFile,BufFilePre,BufRead *.md set filetype=markdown.pandoc
        autocmd FileType markdown.pandoc setlocal conceallevel=0
        autocmd FileType markdown.pandoc setlocal textwidth=78
        autocmd FileType markdown.pandoc setlocal formatoptions+=a formatoptions+=w
    augroup END

    augroup latex    
        au! BufNewFile,BufRead,BufNewFile *.tex set filetype=tex
        autocmd FileType tex setlocal conceallevel=0
        autocmd FileType tex setlocal textwidth=78
        autocmd FileType tex setlocal formatoptions+=a formatoptions+=w
    augroup END

endif


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Autocomplete configuration

" enable ncm2 for all buffers
autocmd BufEnter * call ncm2#enable_for_buffer()

" IMPORTANT: :help Ncm2PopupOpen for more information
set completeopt=noinsert,menuone,noselect

" Close preview when completion is done
autocmd CompleteDone * pclose


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" LSP configuration

" Required for operations modifying multiple buffers like rename.
set hidden
let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie-wrapper'],
    \ 'python': ['pyls'], 
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'], 
    \ }


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Keybindings

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
nmap zr :call LanguageClient#textDocument_rename()<CR>
nmap zk :call LanguageClient#textDocument_hover()<CR>
nmap zd :call LanguageClient#textDocument_definition()<CR>
nmap zt :call LanguageClient#textDocument_typeDefinition()<CR> " goto type definition
nmap zi :call LanguageClient#textDocument_implementation()<CR> " goto implementation 
nmap zr :call LanguageClient#textDocument_references()<CR>
nmap zs :call LanguageClient#textDocument_documentSymbol()<CR>

" Navigating tabs
nmap ; :
nmap td :bd<CR>
nmap tt :Lf<CR>
nmap . :bnext<CR>
nmap , :bprevious<CR>

" Insert lines
nmap = o<Esc>79a=<Esc>0
nmap - o<Esc>79a-<Esc>0
nmap ~ o<Esc>79a~<Esc>0
