[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

[default_session]
command = "agreety --cmd /bin/bash"
user = "greeter"

# [default_session]
# command = "cage -s -- gtkgreet"
# user = "greeter"

# [initial_session]
# command = "wl river"
# user = "nsv"
