#!/bin/sh
set -eu

which keyd || exit 0

cd ~/.builds

if [ -d "handalf" ]; then
    cd handalf
    git pull
else
    git clone https://github.com/nsbgn/handalf.git
    cd handalf
fi

sudo make install
sudo systemctl restart keyd
