#!/bin/sh
# Gesture recognition
# from <https://git.sr.ht/~stacyharper/lisgd>
# cf. <https://www.laubersheimer.eu/2021/08/08/using-lisgd-and-i3-on-a-convertible-laptop.html#configuring-udev>

set -eu

if grep fedora /etc/os-release; then
    sudo dnf install libX11-devel wayland-devel libinput-devel libudev-devel
    # etcetera
else
    sudo apt install lisgd
fi

RULE=/etc/udev/rules.d/99-lisgd-device.rules
# https://www.laubersheimer.eu/2021/08/08/using-lisgd-and-i3-on-a-convertible-laptop.html#configuring-udev
if [ ! -e "$RULE" ]; then
sudo tee "$RULE" <<EOF
ACTION=="add", SUBSYSTEM=="input", KERNEL=="event[0-20]*", ENV{ID_INPUT_TOUCHSCREEN}=="1", MODE:="0666" GROUP="$USER", SYMLINK+="input/touchscreen"
EOF
fi
