#!/bin/bash
F="$1"
WIDTH="$2"
HEIGHT="$3"
SIZE="$(ls -lh "$F" | cut -d' ' -f5)"
TIME="$(exif --machine-readable --tag=DateTime "$F" 2> /dev/null || echo "!EXIF")"
MODIFIED="(mod. $(date -r "$F" '+%Y-%m-%d'))"
NAME="$(basename "$F")"
echo ${NAME} ${WIDTH}x${HEIGHT} ${SIZE} ${TIME} ${MODIFIED}
