#!/bin/bash

xsetroot -cursor_name left_ptr
feh --no-fehbg --bg-tile ~/.config/feh/bg.gif

# Set decoration geometry
berryc border_width        0
berryc inner_border_width  0
berryc title_height       20
berryc edge_gap  30 10 10 10

# Set decoration colors
# berryc focus_color         b57614
# berryc unfocus_color       c3bba7
# berryc inner_focus_color   b57614
# berryc inner_unfocus_color c3bba7
# berryc text_focus_color    ffffff
# berryc text_unfocus_color  eeeeee
berryc focus_color         b57614
berryc unfocus_color       c3bba7
berryc inner_focus_color   ffffee
berryc inner_unfocus_color ffffee
berryc text_focus_color    403935
berryc text_unfocus_color  c3bba7

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "false"
berryc set_font "Cabin-9"
# berryc set_font "Cascadia Code-7"
# berryc set_font "Lemon-4"
berryc focus_follows_pointer "false"
berryc resize_mask Mod4
berryc move_mask Mod1

picom &
sxhkd ~/.config/sxhkd/berry & # keyboard shortcuts
setxkbmap -option compose:menu & # enable compose key
keynav & # use keyboard for mouse navigation
lxpolkit & # policy kit
unclutter -root -idle 2 & # hide mouse when not in use for two seconds
redshift -m randr -x -l manual -O 5500K # -l 52:5 & # nighttime screen colours
dunst & # notifications
urxvtd -q -f -o & # terminal daemon
lf -server & # file manager daemon
# ~/.config/lemonbar/lemonbar
# stalonetray -bg '#D9D2C2' &
polybar bspwm &
dmenu-mpv --initialise &
