#!/bin/sh
# A simple dmenu interface to the password manager `pass`.
# Dependencies: (Debian) pass coreutils findutils sed wl-clipboard xclip

if [ -z $PASSWORD_STORE_DIR ]; then
    PASSWORD_STORE_DIR="$HOME/.password-store"
fi

if [ ! -z "$WAYLAND_DISPLAY" ]; then
    # TYPIST="wtype -"
    TYPIST="wl-copy --paste-once"
else
    # TYPIST="xdotool type --clearmodifiers --file -"
    TYPIST="xclip -i -selection clipboard"
fi

find $PASSWORD_STORE_DIR/ -iname '*.gpg' \
| sed "s|^$PASSWORD_STORE_DIR/\(.*\).gpg|\1|" \
| sort \
| dmenu -p Password -i $DMENU_OPTS \
| xargs --no-run-if-empty pass show \
| xargs -0 --no-run-if-empty $TYPIST
