#!/bin/sh
# Convert FLAC files to ~mp3~ opus files
set -eu

# parallel -j4 ffmpeg -i {} -qscale:a 0 {.}.mp3 ::: *.flac

# TODO: Do I want these settings?
parallel -j4 ffmpeg -i {} -c:a libopus \
    -b:a 96k -vbr on -compression_level 10 \
    {.}.opus ::: *.flac
