#!/bin/sh
# This is very much a workaround.
#
# Starts a new footclient window; and if there is already a terminal window in 
# focus, starts it in the same working directory as the running one. Crucially, 
# this takes into account the foreground process. Sway version of my `xcwd.sh`.
#
# Inspired by:
# - https://github.com/wknapik/lastcwd
# - https://gist.github.com/viking/5851049
#
# To spawn new terminal instances, foot's wiki recommends the following:
# <https://codeberg.org/dnkl/foot/wiki#spawning-new-terminal-instances-in-the-current-working-directory>. 
# That is, you send an OSC-7 escape sequence to notify foot of its working 
# directory, and then you press Ctrl+Shift+N to open a new window.
#
# The first problem is that this means that you need to have a different 
# shortcut for when you're not focused on `foot` at all. You can easily solve 
# this by just checking the current app id and executing something like `wtype 
# -M ctrl -M shift -k n` if we're already on `foot`.
#
# However, this still means that every terminal process needs to manually send 
# OSC-7. foot's guide only mentions your shell, but what about your file 
# manager or editor? You *could* make Neovim call `chansend(v:stderr, 
# "\e]7;file://…\e\\")` on every directory change... but that's only one 
# application down.
#
# I propose instead to put something like this in the .bashrc:
#
#     if [[ "$TERM" == foot* ]]; then
#         echo -en "\033]176;${TERM}:$$\033\\"
#     fi
#
# This changes the app_id of foot to include the process ID of its bash shell.
# We can use this to find the PID of the current process group leader, from
# which we can find the current directory.
set -eu

wl-cwd(){
    local PID=""
    if [ -e "$SWAYSOCK" ]; then
        PID="$(swaymsg -t get_tree | jq -r '
        first(
            recurse(.nodes[], .floating_nodes[])
            | select(.focused)
            | (.app_id | match("^foot.*:([0-9]+)$").captures[0].string | tonumber)
            // .pid
        )')"
    fi
    readlink /proc/$(ps p "$PID" -o tpgid= --delimiter , 2> /dev/null)/cwd || echo "$HOME"
}

if [ -e "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; then
    footclient -D "$(wl-cwd)" "$@"
else
    foot -D "$(wl-cwd)" "$@"
fi
