#!/bin/sh
# A hacky way to either open the `foot` terminal, or spawn a new `foot`
# terminal in the same directory as the currently opened one. For this to work,
# you must use the OSC-7 escape sequence. See also:
# <https://codeberg.org/dnkl/foot/wiki#user-content-spawning-new-terminal-instances-in-the-current-working-directory>
#
# Dependencies:
# - <https://codeberg.org/dnkl/foot>
# - <https://git.sr.ht/~leon_plickat/lswt>
# - <https://github.com/atx/wtype>

is_foot(){
    swaymsg -t get_tree | jq -e \
        '.. | (.nodes? // empty)[] | select(.focused and .app_id == "foot")'
    # alternative:
    # lswt -j | jq -e '.[] | select(.activated and .app_id == "foot")'
}

if is_foot; then
    wtype -M ctrl -M shift -k n
else
    footclient $@
fi
