#!/bin/bash
# <https://github.com/ipodnerd3019/mira-js> for JS
# <https://github.com/elithper/miractl> for Python
# <https://github.com/clarkema/miractl> for Rust
# <https://onyxboox.com/boox_mirapro> for official version
# I use the Rust version now.

# Display Quality: Normal > Speed > A2 > X
# Refresh Speed: X > A2 > Speed > Normal

install(){
    sudo tee /etc/udev/rules.d/58-hid.rules << EOF
SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0416", ATTRS{idProduct}=="5020", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw*", ATTRS{idVendor}=="0416", ATTRS{idProduct}=="5020", MODE="0666", GROUP="plugdev"
EOF
    udevadm control --reload-rules && udevadm trigger
}

if miractl detect; then
    miractl set \
        --speed 4 \
        --contrast 5 \
        --warm 20 \
        --cold 10 \
        --refresh-mode grey \
        --filter 10:96
else
    echo Not connected.
fi
