#!/bin/sh
# Continuously output currently playing song for displaying in polybar or
# lemonbar.
# cf. https://www.reddit.com/r/Unicode/comments/pbq3vp/how_do_i_create_black_and_white_emojis/

# playerctl --no-messages --follow --format '{{status}} {{artist}}' metadata 2>/dev/null \
#     | awk -v l=100 'NF {gsub(/^Playing/,"");gsub(/^Paused/,"");gsub(/^Stopped.*/,""); if (length($0) > l) print substr($0, 1, l-3) "..."; else print; fflush();}'

playerctl --no-messages --follow \
    --format '{{emoji(status)}} {{artist}}' metadata
