#!/bin/sh
# Python env
set -eu

VENV=venv
sudo apt install -y python3-venv

if [ ! -d "$VENV" ]; then
    python3 -m venv "$VENV"
    source "$VENV/bin/activate"
    pip install python-lsp-server[all] mypy pylsp-mypy
fi

