#!/bin/bash

read NAME TRANSFORM < <(swaymsg -t get_outputs \
    | jq -r '.[] | select(.active) | .name+" "+((((.transform | if . == "normal" then 0 else tonumber end)+90)%360)|tostring)')

swaymsg output "$NAME" transform "$TRANSFORM"
