#!/usr/bin/env python3
# import i3ipc as i3  # type: ignore
import i3ipc_extension as i3e
from typing import Iterator

conn = i3e.Connection(prefix="halfwm", auto_reconnect=True)

# @conn.handle_event(i3.Event.WINDOW_NEW)
# def new_window(event: i3.Event) -> Iterator[str]:
#     ...


@conn.handle_message("push")
def push(args: list[str]) -> Iterator[str]:
    tree = conn.get_tree()
    x = args[0]
    if x == 'first':
        yield ''
    elif x == 'second':
        yield ''


conn.main()
