#!/bin/sh
# Wrapper script for Wayland compositors
# Also cf https://man.sr.ht/%7Ekennylevinsen/greetd/

case "$1" in
    gnome)
        CMD="dbus-run-session gnome-session"
        ;;
    sway|wayfire|river|labwc)
        CMD="$1"
        ;;
    foot)
        CMD="cage -s -r -d -- foot -c $HOME/.config/foot/foot-dark.ini"
        ;;
    xournalpp)
        CMD="cage -s -r -d -- xournalpp"
        ;;
    *)
        echo "What's this then"
        exit 1
        ;;
esac

export XKB_DEFAULT_OPTIONS="compose:menu"
export XDG_SESSION_TYPE=wayland
# export XDG_RUNTIME_DIR=/run/user/$(id -u)/
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND=wayland
# export QT_QPA_PLATFORM=wayland-egl
# export ECORE_EVAS_ENGINE=wayland-egl
# export ELM_ENGINE=wayland_egl
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export NO_AT_BRIDGE=1
export GDK_BACKEND=wayland,x11
# export XDG_SESSION_TYPE=x11
# export GDK_BACKEND=x11
export MOZ_USE_XINPUT2=1  # Enable touch scrolling on firefox

# systemd-cat --identifier=sway sway $@

# Avoid slow startup of GTK apps. See /etc/X11/xinit/xinitrc
dbus-update-activation-environment --verbose --systemd --all

exec $CMD
