#!/bin/sh
# Open a file under the assumption that no X display is available

f="${1}"

# Things to consider:
# - Prefer terminal?
# - Suppress terminal output?
# - Is X running? (xset q &>/dev/null)

case $(file --dereference --mime-type "$f" -b) in
    inode/directory)
        lf "$f"
        ;;
    inode/x-empty) 
        nvim "$f" 
        ;;
    text/html)
        firefox "$f"
        ;;
    text/*) 
        nvim "$f"
        ;;
    video/*) 
        mpv --no-terminal "$f" &
        # use --vo=gpu --gpu-context=drm if no X server
        ;;
    audio/midi)
        timidity "$f"
        ;;
    audio/*) 
        mpv "$f"
        ;;
    image/*) 
        sxiv -a "$f" "$(dirname "$f")" &
        ;;
    application/epub+zip) 
        mupdf -r 70 "$f" &
        #epr "$f" within terminal
        ;;
    application/zip)
        EXT="$(echo "${f##*.}" | tr '[:upper:]' '[:lower:]')"
        case $EXT in
            cbz)
                zathura "$f" &
                ;;
            *)
                xdg-open "$f"
                ;;
        esac
        ;;
    application/x-rar)
        EXT="$(echo "${f##*.}" | tr '[:upper:]' '[:lower:]')"
        case $EXT in
            cbr)
                zathura "$f" &
                ;;
            *)
                xdg-open "$f"
                ;;
        esac
        ;;
    application/pdf) 
        zathura "$f" &
        ;;
    application/x-wii-rom)
        dolphin-emu --exec="$f" &
        ;;
    application/x-gba-rom|application/x-gameboy-rom)
        retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/mgba_libretro.so" "$f"
        ;;
    application/x-n64-rom)
        retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/mupen64plus_libretro.so" "$f"
        ;;
    application/x-nintendo-ds-rom)
        retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/desmume_libretro.so" "$f"
        ;;
    application/x-nes-rom)
        retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/nestopia_libretro.so" "$f"
        ;;
    application/octet-stream)
        EXT="$(echo "${f##*.}" | tr '[:upper:]' '[:lower:]')"
        case $EXT in
            zim)
                kiwix-desktop "$f"
            ;;
            sfc)
                retroarch -L "/usr/lib/x86_64-linux-gnu/libretro/bsnes_mercury_balanced.so" "$f"
            ;;
        esac
        ;;
    message/rfc822)
        kmail --view "$f" &
        ;;
    *)
        xdg-open "$f"
        ;;
esac

