#!/bin/bash

PACKAGES=(
    # Utilities
    gnupg # Encrypt files and emails
    pass # Simple password manager based on gnupg
    jq # Parsing JSON
    gojq # Go implementation of jq, with YAML support
    pamixer # Controlling pulseaudio
    aerc # TUI email client
    alacritty # Another terminal
    bat # Cat with highlighting
    black # Python3 code formatter
    brightnessctl # Controlling the backlight
    curl # Retrieve files from the web
    dtrx # Unzipping various formats
    fd-find # Search for files on the filesystem; `find` alternative
    firefox-esr # Web browser
    git # Version control
    gnumeric # lightweight spreadsheets
    graphicsmagick # Imagemagick: Graphics processing
    hexyl # CLI hex viewer
    htop # System monitor
    imv # Image viewer
    innoextract # Extract from Windows installers
    jqp # Playground for gojq
    k2pdfopt # PDF reflow
    khal # TUI calendar
    khard # TUI vcards
    kiwix # Offline reader
    latexdiff # Annotate changes in latex files
    lf # File browser
    lowdown # Markdown processor and terminal viewer
    moreutils # Contains `vipe`, which can edit data between pipes
    mpv # Video viewer
    ncdu # See size of directories
    offlineimap3 # Offline syncer for IMAP email
    otpclient otpclient-cli # TOTP authentication
    pandoc # Document converter
    parallel # Execute commands in parallel
    playerctl # Controlling MPRIS media players
    puddletag # Tagging audio files
    rename # Use like `rename 's/S([0-9]*)E([0-9]*) (.*)/$1x$2 $3/g' *.mkv`
    rfkill # Enabling & disabling wireless
    ripgrep # Search directories for a regex pattern
    rsync # Synchronizing files
    secure-delete # Delete directories securely, like shred
    telegram-desktop # Chat application
    texlive-{fonts-extra,latex-extra,latex-recommended,science} # LaTeX
    tig # Git TUI frontend
    tmux # Attach and detach from terminal sessions/tiling for terminal
    util-linux # System utilities like checking filesystem, block devices..
    vdirsyncer # Synchronise CalDAV and CardDAV
    visidata # Terminal CSV viewer
    webext-browserpass # `pass` plugin
    webext-ublock-origin-firefox # Ad blocker
    wget # Retrieve files from the web
    xournalpp # Drawing & PDF annotations
    xq # XML processor, like jq or htmlq
    zathura{,-cb,-ps,-djvu,-pdf-poppler} # PDF viewer
    zim-tools

    # Build stuff
    gcc
    make
    build-essential

    # Dependencies for scripts
    pipx  # pip with auto venv
    python3-gi  # For dmenu-apps
    python3-yaml  # For crsync
    python3-pypandoc # For download-article
    python3-readability # Should be for download-article
    shntool cuetools  # For split-flac-from-cue

    # Python LSP
    python3-pylsp  # Language server
    python3-pylsp-black  # Autoformatter
    python3-pylsp-rope  # Completions, renaming
    python3-pylsp-isort  # Automatic import sorting
    python3-flake8  # Error checking
    python3-pep8-naming  # PEP8 naming
)

sudo apt update -y
sudo apt upgrade -y
sudo apt install -y ${PACKAGES[@]}
