#!/bin/bash

# Pipe all module updates into a single fifo
STATUS_FIFO=/tmp/lemonbar_statuses
[ -e "$STATUS_FIFO" ] && rm "$STATUS_FIFO"
mkfifo "$STATUS_FIFO"
for MODULE in ./mod_*.sh; do
    NAME="${MODULE#./mod_}"
    NAME="${NAME%.sh}"
    "${MODULE}" | sed -u "s/^/${NAME} /g" > "$STATUS_FIFO" &
done


# Combine statuses into a single line
function statusline {
    declare -A m
    while read -r module content; do
        m["$module"]="$content"
        echo "%{l}${apps} ${bspwm} ${m[title]} %{r}${music} ${volume} ${wifi} ${battery} ${clock} ${power}"
    done
}

# Run the bar
cat "$STATUS_FIFO" | statusline | lemonbar \
    -g x30 \
    -f "-windows-dina-medium-r-normal--10-*-*-*-c-*-iso8859-1" \
    -F "#fff" \
    -B "#000" \
    -u 2 | sh &
