#!/bin/bash
# Show battery status

BATTERY=$(find -L /sys/class/power_supply -mindepth 1 -maxdepth 1 \
    -exec grep -qw {}/type -e Battery \; -print | head -n1 | cut -d'/' -f5)

while [ ! -z "${BATTERY}" ]; do
    echo "%{O2}$(cat /sys/class/power_supply/${BATTERY}/capacity)"
    sleep 30
done

# acpitool -b | tail -n1 | tr -s ' :.' '\t' | cut -f4
