#!/bin/sh
# Show PulseAudio volume
#   Dependencies: amixer, pactl

ICON_NOISE="%{O2}" # siji:  / nf*: 墳
ICON_MUTE="%{O2}" # siji:  / mdi: 

volume() {
    LEVEL="$(amixer sget Master \
        | sed -n 's/.* \[\([0-9]\+\)%\] \[on\]/\1/p' \
        | tail -n1)"
    echo -n "%{A:pactl set-sink-mute @DEFAULT_SINK@ toggle:}"
    if [ -z "${LEVEL}" ]; then
        echo -n "${ICON_MUTE}--"
    else
        echo -n "${ICON_NOISE}${LEVEL}"
    fi
    echo '%{A}'
}

volume
pactl subscribe \
    | grep --line-buffered sink \
    | while read -r line; do volume; done
