#!/bin/sh
# Currently playing song

ICON_PLAY="%{O2}" # siji:  / nf*: 
ICON_PAUSE="%{O2}" # siji:  / nf*: 

playerctl --no-messages --follow --format '{{status}}{{title}} ({{artist}} - {{album}})' metadata 2>/dev/null \
    | awk -v l=100 "NF {gsub(/^Playing/,\"$ICON_PLAY\");gsub(/^Paused/,\"$ICON_PAUSE\");gsub(/^Stopped.*/,\"\"); if (length($$0) > l) print substr($$0, 1, l-3) \"...\"; else print; fflush();}"
