#!/bin/bash
# Show bspwm desktops as dice icons representing the number of windows

DICE_SIJI="s/0//;s/1//;s/2//;s/3//;s/4//;s/5//"
DICE_NERDFONT_MDI="s/0//;s/1//;s/2//;s/3//;s/4//;s/5//;s/6//;s/*/ﱬ/"

PAD="%{O3}"
ICON0="" # siji:  / nf-mdi*: 
ICON1="" # siji:  / nf-mdi*: 
ICON2="" # siji:  / nf-mdi*: 
ICON3="" # siji:  / nf-mdi*: 
ICON4="" # siji:  / nf-mdi*: 
ICON5="" # siji:  / nf-mdi*: 
ICON6="" # nf-mdi*: 
ICONZ="*" # nf-mdi*: ﱬ
ICON_URGENT="!" # nf-mdi*: 


# Return the number of windows in the given desktop as a dice icon
function dice {
    bspc query --nodes --desktop "${1}" --node .window | wc -l

    # bspc query --nodes --desktop "${1}" --node .window \
    #     | tail -n 5 | wc -l \
    #     | sed "s/0/$ICON0/;s/1/$ICON1/;s/2/$ICON2/;s/3/$ICON3/;s/4/$ICON4/;s/5/$ICON5/;s/6/$ICON6/;s/*/$ICONZ/"
}

IFS=':'
bspc subscribe report | while read -r REPORT; do
    L=""
    for R in $REPORT; do
      case $R in
        F*|U*|O*)
            L+="%{A:bspc desktop ${R#?} -f:}%{+u}$PAD$(dice "${R#?}")$PAD%{-u}%{A}"
            ;;
        f*)
            L+="%{A:bspc desktop ${R#?} -f:}$PAD-$PAD%{A}"
            ;;
        o*)
            L+="%{A:bspc desktop ${R#?} -f:}$PAD$(dice "${R#?}")$PAD%{A}"
            ;;
        u*)
            L+="%{A:bspc desktop ${R#?} -f:}$PAD$ICON_URGENT$PAD%{A}"
            ;;
      esac
    done
    echo "$L"
done
