theme = "github_light_high_contrast"

# Remapping in file explorer picker:
# https://github.com/helix-editor/helix/issues/5505

[editor]
text-width = 79

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = "" # ↪

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w"
";" = "command_mode"
